
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Matthias
 */
public class AppointmentDlg extends javax.swing.JDialog {

    private boolean ok;
    private Appointment appointment;
    /**
     * Creates new form AppointmentDlg
     */
    public AppointmentDlg(java.awt.Frame parent, boolean modal, Appointment a) {
        super(parent, modal);
        initComponents();
        this.appointment = a;
        this.tfJahr.setText(a.getDate().getYear()+"");
        this.tfMonat.setText(a.getDate().format(DateTimeFormatter.ofPattern("MM")));
        this.tfTag.setText(a.getDate().getDayOfMonth()+"");
        this.tfStunde.setText(a.getDate().getHour()+"");
        this.tfMinute.setText(a.getDate().getMinute()+"");
        this.tfText.setText(a.getText());
    }

    public boolean isOk() {
        return ok;
    }

    public Appointment getAppointment() {
        return appointment;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTag = new javax.swing.JLabel();
        tfTag = new javax.swing.JTextField();
        lbMonat = new javax.swing.JLabel();
        tfMonat = new javax.swing.JTextField();
        lbJahr = new javax.swing.JLabel();
        tfJahr = new javax.swing.JTextField();
        lbStunde = new javax.swing.JLabel();
        tfStunde = new javax.swing.JTextField();
        lbMinute = new javax.swing.JLabel();
        tfMinute = new javax.swing.JTextField();
        lbText = new javax.swing.JLabel();
        tfText = new javax.swing.JTextField();
        btUebernehmen = new javax.swing.JButton();
        btAbbrechen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(7, 2));

        lbTag.setText("Tag:");
        getContentPane().add(lbTag);

        tfTag.setText("08");
        getContentPane().add(tfTag);

        lbMonat.setText("Monat:");
        getContentPane().add(lbMonat);

        tfMonat.setText("09");
        getContentPane().add(tfMonat);

        lbJahr.setText("Jahr:");
        getContentPane().add(lbJahr);

        tfJahr.setText("2014");
        getContentPane().add(tfJahr);

        lbStunde.setText("Stunde:");
        getContentPane().add(lbStunde);

        tfStunde.setText("08");
        getContentPane().add(tfStunde);

        lbMinute.setText("Minute:");
        getContentPane().add(lbMinute);

        tfMinute.setText("45");
        getContentPane().add(tfMinute);

        lbText.setText("Text");
        getContentPane().add(lbText);

        tfText.setText("POS1-Workshop");
        getContentPane().add(tfText);

        btUebernehmen.setText("übernehmen");
        btUebernehmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUebernehmenActionPerformed(evt);
            }
        });
        getContentPane().add(btUebernehmen);

        btAbbrechen.setText("abbrechen");
        btAbbrechen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbbrechenActionPerformed(evt);
            }
        });
        getContentPane().add(btAbbrechen);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btUebernehmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUebernehmenActionPerformed
        String s = String.format("%s-%s-%s-%s-%s",
                ("0000"+tfJahr.getText()).substring(tfJahr.getText().length()),
                ("00"+tfMonat.getText()).substring(tfMonat.getText().length()),
                ("00"+tfTag.getText()).substring(tfTag.getText().length()),
                ("00"+tfStunde.getText()).substring(tfStunde.getText().length()),
                ("00"+tfMinute.getText()).substring(tfMinute.getText().length()));
        
        //String s1 = tfJahr.getText()+"-"+tfMonat.getText()+"-"+tfTag.getText()+"-"+tfStunde.getText()+"-"+tfMinute.getText();
        LocalDateTime date = LocalDateTime.parse(s,
                DateTimeFormatter.ofPattern("yyyy-MM-dd-HH-mm"));
        appointment = new Appointment(date, tfText.getText());
        ok = true;
        this.dispose();
    }//GEN-LAST:event_btUebernehmenActionPerformed

    private void btAbbrechenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbbrechenActionPerformed
        ok = false;
        this.dispose();
    }//GEN-LAST:event_btAbbrechenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AppointmentDlg dialog = new AppointmentDlg(new javax.swing.JFrame(), true, new Appointment(LocalDateTime.now(), "Text"));
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbbrechen;
    private javax.swing.JButton btUebernehmen;
    private javax.swing.JLabel lbJahr;
    private javax.swing.JLabel lbMinute;
    private javax.swing.JLabel lbMonat;
    private javax.swing.JLabel lbStunde;
    private javax.swing.JLabel lbTag;
    private javax.swing.JLabel lbText;
    private javax.swing.JTextField tfJahr;
    private javax.swing.JTextField tfMinute;
    private javax.swing.JTextField tfMonat;
    private javax.swing.JTextField tfStunde;
    private javax.swing.JTextField tfTag;
    private javax.swing.JTextField tfText;
    // End of variables declaration//GEN-END:variables
}
